# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-24 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_educations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_data',
        ),
    ]
